allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext {
    flutter = [
        compileSdkVersion: 36,
        ndkVersion: "27.0.12077973",
        minSdkVersion: 23,
        targetSdkVersion: 34,
        versionCode: 1,
        versionName: '1.0'
    ]
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
